### ISSUE TITLE
Output binary scts and use proper packages

### ISSUE THREAD

**Issue by rugk** [jbvignaud/cts-submit#5]
Actually you seem to use some kind of workaround to use it with Apache.
The proper way is to use [`mod_ssl_ct`](https://httpd.apache.org/docs/trunk/mod/mod_ssl_ct.html) (or [`nginx-ct`](https://github.com/grahamedgecombe/nginx-ct) with nginx) and there the `.sct` file must be binary and not base64 encoded.

**Comment by jbvignaud** [comment]
I know this extention but it's for apache 2.5. 
I created this script for me and shared it. If you need the binary version of scts, you can remove the base64 encoding and the headers.
