### ISSUE TITLE
Certly.io log will be removed

### ISSUE THREAD

**Issue by rugk** [jbvignaud/cts-submit#8]
Google Chrome [won't trust certly.io](https://groups.google.com/a/chromium.org/forum/m/?_escaped_fragment_=msg/ct-policy/nyRtXSWSeaM/sL1gpJEuCQAJ#!msg/ct-policy/nyRtXSWSeaM/sL1gpJEuCQAJ) anymore as it was not available enough.
So I think we don't need to submit certs there anymore. What do you think? Should it be removed from the script?

**Comment by JasonSome** [comment]
Certly.io also stopped their log services. They don't issue any more SCTs. Finally, they told me that for the time being they don't plan to relaunch CT service.
